import { type NextPage } from "next";
import Head from "next/head";
import { createClient } from "next-sanity";
import { GetStaticProps } from "next";
import Card from "../components/Card/Card";
const ErrorPage: NextPage<{ events: Event[] }> = ({ events }) => {
  return (
    <>
      <Head>
        <title>Events</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div></div>
      <main className="flex h-full flex-grow flex-col items-center justify-center bg-white ">
        {/*404 language*/}
        <h1 className="text-6xl font-bold">404</h1>
        <h2 className="text-2xl font-bold">Page Not Found</h2>
      </main>
    </>
  );
};
export default ErrorPage;
